In [1]:
import numpy as np

a=np.arange(10)
np.append(a,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [4]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
#to append 1 in 2d array --add in column at last
print(np.append(b,np.ones((b.shape[0],1)),axis=1))

[[0. 1. 1.]
 [2. 3. 1.]
 [4. 5. 1.]
 [6. 7. 1.]
 [8. 9. 1.]]


In [19]:
#to append random in 2d array --add in column at last
print(np.append(b,np.random.random((b.shape[0],1)),axis=1))

[[0.         1.         0.14946309]
 [2.         3.         0.22118948]
 [4.         5.         0.09339124]
 [6.         7.         0.51208876]
 [8.         9.         0.57133115]]


In [24]:
#add another array elements at last column
c=np.arange(10,15).reshape(5,1)
print(np.append(b,c,axis=1))

[[ 0  1 10]
 [ 2  3 11]
 [ 4  5 12]
 [ 6  7 13]
 [ 8  9 14]]
