In [12]:
import numpy as np
a=np.array([10,23,45,98,55,34,90,4,67,87,23,76,12,56,99])


In [5]:
#returns indices(index) of max element of array in particular axis
np.argmax(a)

np.int64(13)

In [7]:
b=np.random.randint(1,100,24).reshape(6,4)
print(b)

[[66 71 64 32]
 [66 90 20 19]
 [74 31 49 71]
 [59 87 11  1]
 [71 29 23 50]
 [78 18 64 59]]


In [8]:
#columnwise
np.argmax(b,axis=0)

array([5, 1, 0, 2])

In [9]:
#row wise
np.argmax(b,axis=1)

array([1, 1, 0, 1, 0, 0])

In [13]:
#returns indices(index) of min element of array in particular axis
np.argmin(a)

np.int64(7)

In [14]:
#columnwise
np.argmin(b,axis=0)

array([3, 5, 3, 3])

In [15]:
#row wise
np.argmin(b,axis=1)

array([3, 3, 1, 3, 2, 1])