In [2]:
import numpy as np

a=np.arange(10).reshape(5,2)
b=np.arange(10,20).reshape(5,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [7]:
#rows
print(np.concatenate((a,b),axis=0))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [8]:
#columns
print(np.concatenate((a,b),axis=1))

[[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]
 [ 6  7 16 17]
 [ 8  9 18 19]]
