In [6]:
import numpy as np
a=np.array([10,23,45,98,55,34,90,4,67,87,23,76,12,56,99])
b=np.arange(18).reshape(6,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [3]:
#used when we want to compute cumulative sum of array elements over given axis---it is like sum() window fun in sql
np.cumsum(a)

array([ 10,  33,  78, 176, 231, 265, 355, 359, 426, 513, 536, 612, 624,
       680, 779])

In [9]:
#columnswise
np.cumsum(b,axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26],
       [30, 35, 40],
       [45, 51, 57]])

In [10]:
#row wise
np.cumsum(b,axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30],
       [12, 25, 39],
       [15, 31, 48]])

In [14]:
#cumprod
a=np.arange(1,10)

#used when we want to compute cumulative product of array elements over given axis
np.cumprod(a)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])