In [1]:
import numpy as np
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
#delete items by passing index number
np.delete(a,2)

array([10, 11, 13, 14, 15, 16, 17, 18, 19])

In [3]:
#delete many items
np.delete(a,[0,1,4])

array([12, 13, 15, 16, 17, 18, 19])