In [3]:
import numpy as np
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
np.flip(a)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [4]:
b=np.arange(1,21).reshape(5,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [5]:
#on 2d ---either row wise or column wise
np.flip(b)

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [6]:
#row wise
np.flip(b,axis=0)

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [7]:
#column wise
np.flip(b,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13],
       [20, 19, 18, 17]])