In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array([3,4,5,6,7,8,9])
print(a)
print(b)

[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]


In [2]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.intersect1d(a,b)

array([3, 4, 5, 6, 7])

In [4]:
np.setdiff1d(a,b)

array([1, 2])

In [5]:
np.setxor1d(a,b)

array([1, 2, 8, 9])

In [8]:
np.in1d(a,2)

C:\Users\SUBODH\AppData\Local\Temp\ipykernel_1752\1646599517.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,2)


array([False,  True, False, False, False, False, False])