In [2]:
import numpy as np

a=np.random.randint(1,100,15)
a

array([77, 61, 17, 16, 19, 46, 45,  6, 45, 67, 38, 42, 92, 28, 62],
      dtype=int32)

In [3]:
#2D
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[58, 12, 11, 11],
       [12, 90, 59, 26],
       [ 2, 86, 43, 38],
       [62, 82, 54,  1],
       [16, 10, 75, 14],
       [87, 88,  9, 98]], dtype=int32)

In [10]:
#sort
print(np.sort(a))

#descending
print(np.sort(a)[::-1])

[ 6 16 17 19 28 38 42 45 45 46 61 62 67 77 92]
[92 77 67 62 61 46 45 45 42 38 28 19 17 16  6]


In [6]:
#2D
np.sort(b)

array([[11, 11, 12, 58],
       [12, 26, 59, 90],
       [ 2, 38, 43, 86],
       [ 1, 54, 62, 82],
       [10, 14, 16, 75],
       [ 9, 87, 88, 98]], dtype=int32)

In [8]:
np.sort(b,axis=0)

array([[ 2, 10,  9,  1],
       [12, 12, 11, 11],
       [16, 82, 43, 14],
       [58, 86, 54, 26],
       [62, 88, 59, 38],
       [87, 90, 75, 98]], dtype=int32)