In [1]:
import numpy as  np

a1=np.random.random((3,3))
a2=np.round(a1*100)
print(a1)
print(a2)

[[0.79424393 0.68632799 0.57951758]
 [0.97005122 0.93712137 0.99660133]
 [0.87504253 0.04563245 0.06708007]]
[[ 79.  69.  58.]
 [ 97.  94. 100.]
 [ 88.   5.   7.]]


In [8]:
#max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

#to cal max row wise----axis 1 means row and 0 means col
print(np.max(a1,axis=1))
print(np.max(a1,axis=0))

0.9966013256764288
0.04563244818975143
5.951618439454619
0.0007665855279804601
[0.79424393 0.99660133 0.87504253]
[0.97005122 0.93712137 0.99660133]


In [17]:
#mean/median/std/var

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))



#by colwise or row wise
print(np.mean(a1,axis=1))
print(np.median(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))


0.66129093771718
0.7942439252098304
0.34747506700984254
0.12073892219349457
[0.6866965  0.96792464 0.32925168]
[0.68632799 0.97005122 0.06708007]
[0.08766205 0.02432911 0.38603172]
[0.00768464 0.00059191 0.14902049]


In [18]:
#trignometric function

print(np.sin(a1))

[[0.71333393 0.63370087 0.54762034]
 [0.82491467 0.80585697 0.83962982]
 [0.76757076 0.04561661 0.06702977]]


In [19]:
#dot product
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)

print(np.dot(a1,a2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [21]:
#log and exponents

print(np.log(a2))
print(np.exp(a1))

[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [29]:
#round/floor/ceil
a1=np.random.random((2,3))*100
print(a1)
print(np.round(a1))
print(np.floor(a1))
print(np.ceil(a1))

[[14.41882409 82.86469314 57.0513864 ]
 [32.98455909 34.43470888 33.21218439]]
[[14. 83. 57.]
 [33. 34. 33.]]
[[14. 82. 57.]
 [32. 34. 33.]]
[[15. 83. 58.]
 [33. 35. 34.]]
