In [2]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#2D and 3D
b=np.array([[1,2,3],[3,4,5]])
print(b)
c=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(c)

[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [7]:
#dtype
a=np.array([1,2,3], dtype=float)
print(a)

a=np.array([1,2,3], dtype=bool)
print(a)

a=np.array([1,2,3], dtype=complex)
print(a)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [10]:
#np.arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#with reshape()
np.arange(1,11).reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
#np.ones and np.zeros
ones=np.ones((3,4))
print(ones)

zeros=np.zeros((3,4))
print(zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
#np.random()

np.random.random((3,4))

array([[0.65729314, 0.01354484, 0.38428388, 0.07505192],
       [0.8638684 , 0.60368655, 0.36054666, 0.51222356],
       [0.51853719, 0.63337941, 0.15636217, 0.10682697]])

In [18]:
#np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [19]:
#np.identity()
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.empty(5, dtype=int)

array([            0, 1767189885856, 1767189885056, 1767189883776,
           727449630])

In [21]:
np.empty((2, 2))

array([[0.00000000e+000, 8.73107812e-312],
       [8.73107811e-312, 8.73107813e-312]])