In [7]:
import numpy as np

a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
##indexing

In [9]:
#1D
print(a1)
print(a1[1])
print(a1[-2])

[0 1 2 3 4 5 6 7 8 9]
1
8


In [12]:
#2D
print(a2)
print(a2[2,2])
print(a2[1,2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
6


In [21]:
#3D
print(a3)

print(a3[1,0,1])
print(a3[0,0,1])
print(a3[0,0,0])
print(a3[1,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
1
0
6


In [ ]:
##slicing

In [24]:
#1D
print(a1)
print(a1[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [ ]:
##2D

In [35]:
#2D
print(a2)

#to fetch first row
print(a2[0,:])

#to fetch 3rd col
print(a2[:,2])

#to print 5 6 9 10
print(a2[1:,1:3])

#to print elements from corner 0 3 8 11
print(a2[::2,::3])

#to print 1 3 9 11
print(a2[::2,1::2])

##to print 4 7
print(a2[1,::3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]


In [ ]:
##3D

In [40]:
#3D
a3=np.arange(27).reshape(3,3,3)
print(a3)

#fetch center 2D array
print(a3[1])

#
print(a3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [45]:
print(a3)

#fetch 3 4 5
print(a3[0,1,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]


In [44]:
#fetch 10 13 16
print(a3[1,:,1])

[10 13 16]


In [46]:
#fetch 22 23 25 26
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [65]:
#fetch 0 2 18 20
print(a3[::2,0,])

[[ 0]
 [18]]
