In [3]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)

print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
# using nditer()

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
