In [1]:
import numpy as np

#reshape

a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
#temperoary
#transpose
print(np.transpose(a))
print(a)
print(a.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [5]:
#ravel()
print(np.ravel(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
