In [4]:
import numpy as np

a=np.arange(12).reshape(3,4)
a1=np.arange(12,24).reshape(4,3)

print(a)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [6]:
##horizontaly splitting
print(np.hsplit(a,2))
print(np.hsplit(a,4))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [5]:
#vertically splitting
print(np.vsplit(a1,2))


[array([[12, 13, 14],
       [15, 16, 17]]), array([[18, 19, 20],
       [21, 22, 23]])]
