In [1]:
import numpy as np

a=np.arange(12).reshape(3,4)
a1=np.arange(12,24).reshape(3,4)

print(a)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
##do to stacking shape of array wants same like here (3,4)

In [4]:
#horizontaly stacking
print(np.hstack((a,a1)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [5]:
#vertically stacking
print(np.vstack((a,a1)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
