In [ ]:
#Numpy Array VS Python List
#speed
#memory

In [6]:
#Advanced Indexing

import numpy as np
a=np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [9]:
#fancy indexing

#to fetch rows
print(a[[0,2,3,5]])

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]


In [10]:
#to fetch cols
print(a[0:,[0,2,3]])

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [12]:
#Boolean Indexing
a2=np.random.randint(1,100,24).reshape(6,4)
print(a2)

[[81 97 96 89]
 [ 2 91 50 41]
 [55 80 62 35]
 [13 84 74 34]
 [33 47 38 45]
 [77 61 33 68]]


In [14]:
#find all numbers from a2 which are greater than 50
print(a2[a2>50])

[81 97 96 89 91 55 80 62 84 74 77 61 68]


In [15]:
#find out even numbers
print(a2[a2%2==0])

[96  2 50 80 62 84 74 34 38 68]


In [26]:
#find all numbers greater than 50 and are even
print(a2[(a2>50) & (a2%2==0)])

#find all numbers greater than 50 or are even
print(a2[(a2>50) | (a2%2==0)])

[96 80 62 84 74 68]
[81 97 96 89  2 91 50 55 80 62 84 74 34 38 77 61 68]


In [25]:
#find all numbers not divisible by 7
print(a2[a2%7 !=0])
print(a2[~(a2%7==0)])

#find all numbers divisible by 7
print(a2[a2%7==0])

[81 97 96 89  2 50 41 55 80 62 13 74 34 33 47 38 45 61 33 68]
[81 97 96 89  2 50 41 55 80 62 13 74 34 33 47 38 45 61 33 68]
[91 35 84 77]
