In [1]:
#Broadcasting
import numpy as np
a=np.arange(6).reshape(2,3)
print(a)
b=np.arange(6,12).reshape(2,3)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [4]:
#diff shape
a=np.arange(6).reshape(2,3)
print(a)
b=np.arange(3).reshape(1,3)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [6]:
#Examples1
a=np.arange(12).reshape(4,3)
b=np.arange(3)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


In [7]:
print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [10]:
#Examples2---throw error bcause (3) not convert into (3,1)
a=np.arange(9).reshape(3,4)
b=np.arange(3)
print(a)
print(b)
print(a+b)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [12]:
#Example3
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [13]:
#Example4
a=np.arange(3).reshape(1,3)
b=np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [15]:
#Example5
a=np.array([3])
b=np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

[3]
[[0 1]
 [2 3]]
[[3 4]
 [5 6]]


In [16]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [17]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 