In [23]:
import numpy as np
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
#scalar operations---operation on one numpy array
print(a1)

#arithmetic operation
print(a1*2)
print(a1**2)

#relational
print(a2>15)
print(a2>5)
print(a1==10)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False  True False]]


In [24]:
#vector---operation two numpy array

#arithmetic
print(a1+a2)
print(a1*a2)

#relational
print(a1<a2)
print(a1>a2)
print(a1+2==a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]
 [False False False False]]
